# Generated by Django 4.1.3 on 2022-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=19)),
                ('weight', models.IntegerField(default=130)),
                ('last_donation', models.DateField(auto_now_add=True)),
                ('wants_to_donate', models.BooleanField(default=False)),
                ('needs_donation', models.BooleanField(default=True)),
            ],
        ),
    ]
