const Data = [
  {
    id: 1,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 2,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 3,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 4,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 5,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 6,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 7,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 8,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 9,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
  {
    id: 10,
    firstName: 'Kingsley',
    lastName: 'Ibe',
    age: '20',
    weight: '60kg',
    location: 'Lagos, Nigeria',
    gender: 'Male',
    genotype: 'AA',
    bloodGroup: 'B+',
    phone: '23478903333',
    email: 'test@test.com',
    donatedBefore: 'Yes',
    donationItem: 'Kidney',
    btn: 'Contact this user',

  },
];

export default Data;
