import React from 'react';

const PolicyDocs = () => (
  <div className="p-10">
    <p className="mb-5">Privacy Policy</p>
    <p>Last updated: November 30, 2022</p>
    <p className="my-5">
      This Privacy Policy describes Our policies and procedures on the collection,
      use and disclosure of Your information when You use the Service and tells You
      about Your privacy rights and how the law protects You.
    </p>
    <p>
      We use Your Personal data to provide and improve the Service.
      By using the Service, You agree to the collection and use of information in
      accordance with this Privacy Policy. This Privacy Policy has been created with
      the help of the
      {' '}
      <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator" target="__blank" className="underline text-[#17a2b8]">Free Privacy Policy Generator.</a>

    </p>
    <h1 className="text-[#17a2b8] text-[35px] font-bold my-10">Interpretation and Definitions</h1>
    <h2 className="text-[#17a2b8] text-[25px] mb-2">Interpretation</h2>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the same
      meaning regardless of whether they appear in the singular or in the plural.
    </p>
    <h2 className="text-[#17a2b8] text-[25px] my-2">Definitions</h2>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the same
      meaning regardless of whether they appear in the singular or in the plural.
    </p>
    <p className="my-5">For the purposes of this Privacy Policy:</p>
    <div className="ml-10">
      <p>
        <b>
          Account
          {' '}

        </b>
        {' '}
        means a unique account created for You to access our Service or
        parts of our Service.
      </p>
      <p>
        <b>
          Company
          {' '}

        </b>
        {' '}
        (referred to as either &#34;the Company&#34;,
        &#34;We&#34;, &#34;Us&#34; or &#34;Our&#34; in this Agreement)
        refers to Life Force, Lagos, Nigeria.
      </p>
      <p>
        <b>
          Cookies
          {' '}

        </b>
        {' '}
        are small files that are placed on Your computer,
        mobile device or any other device by a website, containing the details
        of Your browsing history on that website among its many uses.

      </p>
      <p>
        <b>
          Country
          {' '}

        </b>
        {' '}
        refers to Nigeria

      </p>
      <p>
        <b>
          Device
          {' '}

        </b>
        {' '}
        means any device that can access the Service such as a computer,
        a cellphone or a digital tablet.

      </p>
      <p>
        <b>
          Personal
          {' '}

        </b>
        {' '}
        Data is any information that relates to an identified or identifiable individual.

      </p>
      <p>
        <b>
          Service
          {' '}

        </b>
        {' '}
        refers to the Website.

      </p>
      <p>
        <b>
          Service Provider
          {' '}

        </b>
        {' '}
        means any natural or legal person who processes the data on behalf of
        the Company. It refers to third-party companies or individuals employed by the Company
        to facilitate the Service, to provide the Service on behalf of the Company, to perform
        services related to the Service or to assist the Company in
        analyzing how the Service is used.

      </p>
      <p>
        <b>
          Third-party Social Media Service
          {' '}

        </b>
        {' '}
        refers to any website or any social network
        website through which a User can log in or create an account to use the Service.

      </p>
      <p>
        <b>
          Usage Data
          {' '}

        </b>
        {' '}
        Usage Data refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).

      </p>
      <p>
        <b>
          The website
          {' '}

        </b>
        {' '}
        refers to Life Force, accessible from
        <a href="/" className="underline" target="__blank">http://www.lifeforce.com</a>

      </p>
      <p>
        <b>
          You
          {' '}

        </b>
        {' '}
        mean the individual accessing or using the Service, the company,
        or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.

      </p>
    </div>
    <h1 className="text-[#17a2b8] text-[35px] font-bold my-10">Collecting and Using Your Personal Data</h1>
    <h2 className="text-[#17a2b8] text-[25px] mb-2">Types of Data Collected</h2>
    <h3 className="text-[#17a2b8] text-[18px] mb-2">Personal Data</h3>
    <p>
      While using Our Service, We may ask You to provide Us with certain personally
      identifiable information that can be used to contact or identify You. Personally,
      identifiable information may include, but is not limited to:
    </p>
    <ul className="ml-10">
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Address, State, Province, ZIP/Postal code, City</li>
      <li>National Identity Number (NIN)</li>
      <li>Usage Data</li>
    </ul>
    <h3 className="text-[#17a2b8] text-[18px] mb-2">Usage Data</h3>
    <p>Usage Data has collected automatically when using the Service.</p>
    <p className="my-2">
      Usage Data may include information such as Your Device&#39;s Internet Protocol address
      (e.g. IP address), browser type, browser version, the pages of our Service that You visit,
      the time and date of Your visit, the time spent on those pages, unique device identifiers and
      other diagnostic data.
    </p>
    <p>
      When You access the Service by or through a mobile device, We may collect certain
      information automatically, including, but not limited to, the type of mobile device You use,
      Your mobile device&#39;s unique ID, the IP address of Your mobile device,
      Your mobile operating system,
      the type of mobile Internet browser You use, unique device identifiers
      and other diagnostic data.
    </p>
    <p className="my-2">
      We may also collect information that Your browser sends whenever You visit our Service
      or when You access the Service by or through a mobile device.
    </p>
    <h3 className="text-[#17a2b8] text-[18px] mb-2">
      Information from Third-Party Social Media Services
    </h3>
    <p>
      The Company allows You to create an account and
      log in to use the Service through the
      following Third-party Social Media Services:
    </p>
    <ol className="my-2 ml-10">
      <li>Google</li>
      <li>Facebook</li>
      <li>Twitter</li>
      <li> LinkedIn</li>
    </ol>
    <p>
      Suppose You decide to register through or otherwise grant us access to a
      Third-Party Social Media Service. In that case, We may collect Personal data
      that is already associated with Your Third-Party Social Media Service accounts,
      such as Your name, email address, activities or Your contact list
      associated with that account.
    </p>
    <p className="my-2">
      You may also have the option of sharing additional information with the Company
      through Your Third-Party Social Media Service&#39;s account.
      If You choose to provide such
      information and Personal Data, during registration
      or otherwise, You are giving the Company
      permission to use, share, and store it in a manner
      consistent with this Privacy Policy.
    </p>
    <h3 className="text-[#17a2b8] text-[18px] mb-2">Tracking Technologies and Cookies</h3>
    <p>
      We use Cookies and similar tracking technologies to track the activity on Our Service
      and store certain information. Tracking technologies used are beacons, tags, and scripts to
      collect and track information and to improve and analyze Our Service. The technologies We
      use may include:
    </p>
    <ul className="my-2 ml-10">
      <li>
        <b>Cookies or Browser Cookies. </b>
        A cookie is a small file placed on Your Device. You can instruct Your browser to
        refuse all Cookies or to indicate when a cookie is being sent. However, if You do not
        accept Cookies, You may not be able to use some parts of our Service. Unless you have
        adjusted Your browser setting so that it will refuse cookies, our Service may use Cookies.
      </li>
      <li>
        <b>Web Beacons. </b>
        Certain sections of our Service and our emails may
        contain small electronic files known as web
        beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs)
        that permit the Company,
        for example, to count users who have visited those
        pages or opened an email and for other related
        website statistics (for example, recording the
        popularity of a certain section and verifying system
        and server integrity).
      </li>
    </ul>
    <p>
      Cookies can be &#34;Persistent&#34; or &#34;Session&#34; Cookies. Persistent Cookies remain on
      Your personal computer or mobile device when You go offline, while Session Cookies are
      deleted as soon as You close Your web browser. Learn more about cookies on the
      <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" className="underline" target="__blank">
        Free Privacy Policy website article.
      </a>
    </p>
    <p className="my-2">We use both Session and Persistent Cookies for the purposes set out below:</p>
    <div className="ml-10">
      <h3 className="font-bold">Necessary / Essential Cookies</h3>
      <p>Type: Session Cookies</p>
      <p>Administered by: Us</p>
      <p>
        Purpose: These Cookies are essential to provide
        You with services available through
        the Website and to enable You to use some of its features.
        They help to authenticate users
        and prevent fraudulent use of user accounts.
        Without these Cookies,
        the services that You have
        asked for cannot be provided, and We only use these Cookies to provide
        You with those services.
      </p>
      <h3 className="font-bold mt-2">Cookies Policy / Notice Acceptance Cookies</h3>
      <p>Administered by: Us</p>
      <p>Purpose: These Cookies identify if users have accepted cookies on the Website.</p>
      <h3 className="font-bold mt-2">Functionality Cookies</h3>
      <p>Type: Persistent Cookies</p>
      <p>Administered by: Us</p>
      <p>
        Purpose: These Cookies allow us to remember choices You make when You use the Website,
        such as remembering your login details or language preference. The purpose of these Cookies
        is to provide You with a more personal experience and to avoid You having to re-enter your
        preferences every time You use the Website.
      </p>
    </div>
    <p>
      For more information about the cookies we use and your choices regarding cookies,
      please visit our Cookies Policy or the Cookies section of our Privacy Policy.
    </p>
    <h2 className="text-[#17a2b8] text-[25px] mb-2">Use of Your Personal Data</h2>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li>
        <b>To provide and maintain our Service, </b>
        including monitoring the usage of our Service.
      </li>
    </ul>
  </div>
);

export default PolicyDocs;
