import React from 'react';

const PolicyDocs = () => (
  <div className="p-10">
    <p className="mb-5">Privacy Policy</p>
    <p>Last updated: November 30, 2022</p>
    <p className="my-5">
      This Privacy Policy describes Our policies and procedures on the collection,
      use and disclosure of Your information when You use the Service and tells You
      about Your privacy rights and how the law protects You.
    </p>
    <p>
      We use Your Personal data to provide and improve the Service.
      By using the Service, You agree to the collection and use of information in
      accordance with this Privacy Policy. This Privacy Policy has been created with
      the help of the
      {' '}
      <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator" target="__blank" className="underline text-[#17a2b8]">Free Privacy Policy Generator.</a>

    </p>
    <h1 className="text-[#17a2b8] text-[35px] font-bold my-10">Interpretation and Definitions</h1>
    <h2 className="text-[#17a2b8] text-[25px] mb-2">Interpretation</h2>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the same
      meaning regardless of whether they appear in the singular or in the plural.
    </p>
    <h2 className="text-[#17a2b8] text-[25px] my-2">Definitions</h2>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the same
      meaning regardless of whether they appear in the singular or in the plural.
    </p>
    <p className="my-5">For the purposes of this Privacy Policy:</p>
    <div className="ml-10">
      <p>
        <b>
          Account
          {' '}

        </b>
        {' '}
        means a unique account created for You to access our Service or
        parts of our Service.
      </p>
      <p>
        <b>
          Company
          {' '}

        </b>
        {' '}
        (referred to as either &#34;the Company&#34;,
        &#34;We&#34;, &#34;Us&#34; or &#34;Our&#34; in this Agreement)
        refers to Life Force, Lagos, Nigeria.
      </p>
      <p>
        <b>
          Cookies
          {' '}

        </b>
        {' '}
        are small files that are placed on Your computer,
        mobile device or any other device by a website, containing the details
        of Your browsing history on that website among its many uses.

      </p>
      <p>
        <b>
          Country
          {' '}

        </b>
        {' '}
        refers to Nigeria

      </p>
      <p>
        <b>
          Device
          {' '}

        </b>
        {' '}
        means any device that can access the Service such as a computer,
        a cellphone or a digital tablet.

      </p>
      <p>
        <b>
          Personal
          {' '}

        </b>
        {' '}
        Data is any information that relates to an identified or identifiable individual.

      </p>
      <p>
        <b>
          Service
          {' '}

        </b>
        {' '}
        refers to the Website.

      </p>
      <p>
        <b>
          Service Provider
          {' '}

        </b>
        {' '}
        means any natural or legal person who processes the data on behalf of
        the Company. It refers to third-party companies or individuals employed by the Company
        to facilitate the Service, to provide the Service on behalf of the Company, to perform
        services related to the Service or to assist the Company in
        analyzing how the Service is used.

      </p>
      <p>
        <b>
          Third-party Social Media Service
          {' '}

        </b>
        {' '}
        refers to any website or any social network
        website through which a User can log in or create an account to use the Service.

      </p>
      <p>
        <b>
          Usage Data
          {' '}

        </b>
        {' '}
        Usage Data refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).

      </p>
      <p>
        <b>
          The website
          {' '}

        </b>
        {' '}
        refers to Life Force, accessible from <a href="/" className="underline" target="__blank">http://www.lifeforce.com</a>

      </p>
      <p>
        <b>
          You
          {' '}

        </b>
        {' '}
        mean the individual accessing or using the Service, the company,
        or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.

      </p>
    </div>
  </div>
);

export default PolicyDocs;
